### PR TITLE
Pin libpng 1.6*

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by pelson** [comment]
Can of worms 😄 : 

```
conda execute conda-forge.github.io/scripts/list_deps.py conda-forge --dependencies libpng --platform osx-64
Fetching package metadata: ..
cairo 1.12.18 0 osx-64             : libpng 1.6*
eccodes 0.13.0 0 osx-64            : libpng 1.6*
ecmwf_grib 1.14.7 2 osx-64         : libpng
ecmwf_grib 1.14.7 3 osx-64         : libpng 1.6*
fontconfig 2.11.1 0 osx-64         : libpng
fontconfig 2.11.1 1 osx-64         : libpng 1.6*
freetype 2.6.3 0 osx-64            : libpng 1.6*
gdal 1.11.4 np110py27_4 osx-64     : libpng
gdal 1.11.4 np110py27_5 osx-64     : libpng 1.6*
gdal 1.11.4 np110py27_6 osx-64     : libpng 1.6*
gdal 1.11.4 np110py27_7 osx-64     : libpng 1.6*
gdal 1.11.4 np110py34_4 osx-64     : libpng
gdal 1.11.4 np110py34_5 osx-64     : libpng 1.6*
gdal 1.11.4 np110py34_6 osx-64     : libpng 1.6*
gdal 1.11.4 np110py34_7 osx-64     : libpng 1.6*
gdal 1.11.4 np110py35_4 osx-64     : libpng
gdal 1.11.4 np110py35_5 osx-64     : libpng 1.6*
gdal 1.11.4 np110py35_6 osx-64     : libpng 1.6*
gdal 1.11.4 np110py35_7 osx-64     : libpng 1.6*
gdal 1.11.4 np111py27_4 osx-64     : libpng
gdal 1.11.4 np111py27_5 osx-64     : libpng 1.6*
gdal 1.11.4 np111py27_6 osx-64     : libpng 1.6*
gdal 1.11.4 np111py27_7 osx-64     : libpng 1.6*
gdal 1.11.4 np111py34_4 osx-64     : libpng
gdal 1.11.4 np111py34_5 osx-64     : libpng 1.6*
gdal 1.11.4 np111py34_6 osx-64     : libpng 1.6*
gdal 1.11.4 np111py34_7 osx-64     : libpng 1.6*
gdal 1.11.4 np111py35_4 osx-64     : libpng
gdal 1.11.4 np111py35_5 osx-64     : libpng 1.6*
gdal 1.11.4 np111py35_6 osx-64     : libpng 1.6*
gdal 1.11.4 np111py35_7 osx-64     : libpng 1.6*
gdal 2.0.2 np110py27_3 osx-64      : libpng
gdal 2.0.2 np110py27_4 osx-64      : libpng
gdal 2.0.2 np110py34_3 osx-64      : libpng
gdal 2.0.2 np110py34_4 osx-64      : libpng
gdal 2.0.2 np110py35_3 osx-64      : libpng
gdal 2.0.2 np110py35_4 osx-64      : libpng
gdal 2.0.2 np111py27_3 osx-64      : libpng
gdal 2.0.2 np111py27_4 osx-64      : libpng
gdal 2.0.2 np111py34_3 osx-64      : libpng
gdal 2.0.2 np111py34_4 osx-64      : libpng
gdal 2.0.2 np111py35_3 osx-64      : libpng
gdal 2.0.2 np111py35_4 osx-64      : libpng
gdal 2.1.0 np110py27_0 osx-64      : libpng
gdal 2.1.0 np110py27_1 osx-64      : libpng 1.6*
gdal 2.1.0 np110py34_0 osx-64      : libpng
gdal 2.1.0 np110py34_1 osx-64      : libpng 1.6*
gdal 2.1.0 np110py35_0 osx-64      : libpng
gdal 2.1.0 np110py35_1 osx-64      : libpng 1.6*
gdal 2.1.0 np111py27_0 osx-64      : libpng
gdal 2.1.0 np111py27_1 osx-64      : libpng 1.6*
gdal 2.1.0 np111py34_0 osx-64      : libpng
gdal 2.1.0 np111py34_1 osx-64      : libpng 1.6*
gdal 2.1.0 np111py35_0 osx-64      : libpng
gdal 2.1.0 np111py35_1 osx-64      : libpng 1.6*
matplotlib 1.5.1 np110py27_0 osx-64: libpng 1.6*
matplotlib 1.5.1 np110py34_0 osx-64: libpng 1.6*
matplotlib 1.5.1 np110py35_0 osx-64: libpng 1.6*
matplotlib 1.5.1 np111py27_0 osx-64: libpng 1.6*
matplotlib 1.5.1 np111py34_0 osx-64: libpng 1.6*
matplotlib 1.5.1 np111py35_0 osx-64: libpng 1.6*
matplotlib 1.5.1 np19py35_0 osx-64 : libpng
opencv 2.4.12 np110py27_0 osx-64   : libpng
opencv 2.4.12 np110py27_1 osx-64   : libpng
opencv 2.4.12 np110py27_2 osx-64   : libpng 1.6*
opencv 2.4.12 np111py27_0 osx-64   : libpng
opencv 2.4.12 np111py27_1 osx-64   : libpng
opencv 2.4.12 np111py27_2 osx-64   : libpng 1.6*
opencv 2.4.12 np19py27_0 osx-64    : libpng
openjpeg 2.1.0 1 osx-64            : libpng
openjpeg 2.1.0 2 osx-64            : libpng
openjpeg 2.1.0 3 osx-64            : libpng 1.6*
openjpeg 2.1.0 4 osx-64            : libpng 1.6*
openjpeg 2.1.0 5 osx-64            : libpng 1.6*
pygrib 2.0.1 py27_1 osx-64         : libpng 1.6*
pygrib 2.0.1 py34_1 osx-64         : libpng 1.6*
pygrib 2.0.1 py35_1 osx-64         : libpng 1.6*
pynio 1.5.0beta np110py27_0 osx-64 : libpng
pynio 1.5.0beta np110py27_1 osx-64 : libpng
pynio 1.5.0beta np110py27_2 osx-64 : libpng
pynio 1.5.0beta np111py27_1 osx-64 : libpng
pynio 1.5.0beta np111py27_2 osx-64 : libpng
pynio 1.5.0beta np19py27_0 osx-64  : libpng
python-ecmwf_grib 1.14.7 np110py27_0 osx-64: libpng
python-ecmwf_grib 1.14.7 np110py27_1 osx-64: libpng 1.6*
python-ecmwf_grib 1.14.7 np111py27_0 osx-64: libpng
python-ecmwf_grib 1.14.7 np111py27_1 osx-64: libpng 1.6*
sox 14.4.2 0 osx-64                : libpng
sox 14.4.2 1 osx-64                : libpng 1.6*
sox 14.4.2 2 osx-64                : libpng 1.6*
vigra 1.11.0 np110py27_0 osx-64    : libpng
vigra 1.11.0 np110py27_1 osx-64    : libpng
vigra 1.11.0 np110py27_2 osx-64    : libpng 1.6*
vigra 1.11.0 np110py27_3 osx-64    : libpng 1.6*
vigra 1.11.0 np110py27_4 osx-64    : libpng 1.6*
vigra 1.11.0 np110py34_0 osx-64    : libpng
vigra 1.11.0 np110py34_1 osx-64    : libpng
vigra 1.11.0 np110py34_2 osx-64    : libpng 1.6*
vigra 1.11.0 np110py34_3 osx-64    : libpng 1.6*
vigra 1.11.0 np110py34_4 osx-64    : libpng 1.6*
vigra 1.11.0 np110py35_0 osx-64    : libpng
vigra 1.11.0 np110py35_1 osx-64    : libpng
vigra 1.11.0 np110py35_2 osx-64    : libpng 1.6*
vigra 1.11.0 np110py35_3 osx-64    : libpng 1.6*
vigra 1.11.0 np110py35_4 osx-64    : libpng 1.6*
vigra 1.11.0 np111py27_1 osx-64    : libpng
vigra 1.11.0 np111py27_2 osx-64    : libpng 1.6*
vigra 1.11.0 np111py27_3 osx-64    : libpng 1.6*
vigra 1.11.0 np111py27_4 osx-64    : libpng 1.6*
vigra 1.11.0 np111py34_1 osx-64    : libpng
vigra 1.11.0 np111py34_2 osx-64    : libpng 1.6*
vigra 1.11.0 np111py34_3 osx-64    : libpng 1.6*
vigra 1.11.0 np111py34_4 osx-64    : libpng 1.6*
vigra 1.11.0 np111py35_1 osx-64    : libpng
vigra 1.11.0 np111py35_2 osx-64    : libpng 1.6*
vigra 1.11.0 np111py35_3 osx-64    : libpng 1.6*
vigra 1.11.0 np111py35_4 osx-64    : libpng 1.6*
vigra 1.11.0 np19py27_0 osx-64     : libpng
vigra 1.11.0 np19py27_1 osx-64     : libpng
vigra 1.11.0 np19py34_0 osx-64     : libpng
vigra 1.11.0 np19py34_1 osx-64     : libpng
vigra 1.11.0 np19py35_0 osx-64     : libpng
vigra 1.11.0 np19py35_1 osx-64     : libpng
```


Should we remove all builds which don't pin libpng?

**Comment by ocefpaf** [comment]
> Should we remove all builds which don't pin libpng?

I don't see a better choice :unamused: 

I will do that soon.

**Comment by pelson** [comment]
> I will do that soon.

We can automate that. 😉

**Comment by ocefpaf** [comment]
OK. I will hold the fire.

**Comment by pelson** [comment]
> OK. I will hold the fire.

Unless there is a burning issue, let's put it in the todo at https://github.com/conda-forge/conda-forge.github.io/issues/111. 😉

**Comment by jakirkham** [comment]
Also, I should add that the pinning probably needs to be more precise. See this long and weary tale ( https://github.com/conda-forge/vigra-feedstock/pull/8 ). Fortunately, I think I can wait there until next week. So, we should figure out why there are these platform differences.

**Pull request merged**
