### PR TITLE
Update to 2.13.1

### PR DESCRIPTION
**Pull request by ocefpaf**
Testing...

### CODE REVIEW

**Comment by ocefpaf** [comment]
@pkgw do you have an idea of the Windows and OS X failures?

**Comment by pkgw** [comment]
@ocefpaf For Windows, my guess is that conda isn't searching the msys2 channels for packages ... can our way of specifying the channels of interest somehow accidentally exclude that?

For macOS, I have no idea. There are no errors from the autoreconf so it's very strange that such a low-level error would creep into the configure. Are you able to run a build on a macOS box and examine the configure script directly?

**Comment by ocefpaf** [comment]
> @ocefpaf For Windows, my guess is that conda isn't searching the msys2 channels for packages ... can our way of specifying the channels of interest somehow accidentally exclude that?

Oops! I'm re-rendering with my hacked conda-smithy. Let me fix that...

**Comment by ocefpaf** [comment]
@pkgw now looks like we have a real failure. One, and possibly more, of the patches needs to be refreshed.

**Comment by pkgw** [comment]
Superseded by #38.

**Pull request closed without merging**
