### PR TITLE
Update pinnings...

### PR DESCRIPTION
**Pull request by ocefpaf**
... and re-rendered.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@pelson we also need this to finally fix `matplotlib`.

**Comment by pelson** [comment]
:+1: 

Presumably there are binaries which need removing from anaconda.org too? Could you run https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/list_deps.py to confirm the binaries that need removing, and provide the output here from before & after doing so?

Thanks!

**Comment by ocefpaf** [comment]
On it. But we did not see issues were a low build number was installed ever again. Thanks @mcg1969! I believe that was you, right?

**Comment by mcg1969** [comment]
Oh I'm happy to take credit, even though I have no idea!

**Comment by pelson** [comment]
Channel priority, I believe. :+1:

**Comment by pelson** [comment]
:+1:

**Pull request merged**
