### PR TITLE
Build long prefix package using conda-build 2.x

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by jakirkham** [comment]
Hmm...CircleCI is not starting. 😕

**Comment by jakirkham** [comment]
So I can't build this locally with the docker image either as I run into issue ( https://github.com/conda/conda-build/issues/1302 ). That said, I have no reason to suspect this won't work on CircleCI. Given how important having a rebuilt `fontconfig` is for progressing with `conda-build` 2, I'd like to try this anyways. If it doesn't end up working, we can always try a follow-up PR.

**Comment by jjhelmus** [comment]
> If it doesn't end up working, we can always try a follow-up PR.

Sounds reasonable to me.  +1 for merging

**Comment by jakirkham** [comment]
Note CircleCI does seem to build fine on the branches of the feedstocks. Just not on PRs from forks.

**Comment by jakirkham** [comment]
Thanks Jonathan.

**Comment by jakirkham** [comment]
Looks like it worked on CircleCI.

```
Uploaded /feedstock_root/build_artefacts/linux-64/fontconfig-2.11.1-5.tar.bz2
No packages found with binary prefixes shorter than 255 characters.
```

Travis CI already worked in the PR.

**Comment by jjhelmus** [comment]
Great!  Thanks @jakirkham.  I think this should allow long prefix build for some additional packages (`textlive-core`, `graphviz`).

**Comment by jakirkham** [comment]
Of course. Thank you for getting all of this started. 👍

**Comment by jakirkham** [comment]
Should note that the rebuilt `fontconfig` packages are out. So we should be good to go.

**Pull request merged**
