### PR TITLE
Add windows support

### LINKED ISSUE #18: Windows build???
I'm hoping to do a Windows build of libgd, but it requires fontconfig, and there is currently no Windows build for fontconfig.

Is there a major blocker? or has just no one gotten around to getting it working?

-CHB

### PR DESCRIPTION
**Pull request by pkgw**
After some local prototyping, this should get us providing a static fontconfig library on Windows.

Closes #18.

### CODE REVIEW

**Comment by pkgw** [comment]
And here's the Vagrant setup I put together to help me iterate on the Windows build commands from my Linux box: [pkgw/conda-forge-windows-vagrant-builder](https://github.com/pkgw/conda-forge-windows-vagrant-builder)

**Comment by mingwandroid** [comment]
Should we make msvc import libs here @pkgw? I've been going a slightly different route with these type of packages, building from the msys2 PKGBUILD.

**Comment by pkgw** [comment]
@mingwandroid I ... have no idea? I have a very poor handle on the different possibilities, and which ones will play nicely with fontconfig's autotools-based build system. I am more than happy to iterate on the approach taken here.

For what it's worth, the main library deps of this package, freetype and libxml2, seem to use different naming schemes for the libraries they provide:

```
Library/bin/freetype.dll
Library/lib/freetype.lib
```

libxml2:

```
Library/bin/libxml2.dll
Library/lib/libxml2_a_dll.lib
Library/lib/libxml2_a.lib
Library/lib/libxml2.lib
```

**Comment by pkgw** [comment]
@mingwandroid Looking into this farther ... if I'm understanding correctly, MSVC import libraries are only for when you're providing DLLs, right? At the moment this package only provides static libraries since libtool can't figure out how to link with freetype. I don't think I have an exact copy of the error message here, but if you build without `--disable-shared`, you get a message along the lines of:

```
*** Libtool cannot determine how to link with -lfreetype! ...
```

And something to the effect that it will only produce static libraries since it can't create shared libraries with missing symbols. (If you don't explicitly pass `--disable-shared`, the build gets past that point, but then the install errors out since it expects various `.dll` files to exist that don't.)

**Pull request merged**
