### PR TITLE
Bump to 2.13.94

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fix https://github.com/conda-forge/fontconfig-feedstock/issues/48

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by pkgw** [comment]
Down to a Windows failure:

```
test-issue107.obj : error LNK2019: unresolved external symbol sleep referenced in function main
```

Probably easiest just to disable this specific test?

**Comment by Tobias-Fischer** [comment]
Sorry that I have opened the PR and then not followed up with it. Yes, disabling the patch sounds good to me if that's okay with you (the test just before is skipped on Windows anyhow).

**Comment by pkgw** [comment]
OK, I worked around the previous problem but it looks like we have to just avoid the whole test suite on Windows due to [this issue that I filed upstream](https://gitlab.freedesktop.org/fontconfig/fontconfig/-/issues/307).

These new versions include Meson-based build scripts now, and it might make life easier (especially our Windows and cross-platform builds) to switch to using that instead of the Autotools.

**Comment by pkgw** [comment]
OK, hopefully this is ready to go, although I wouldn't mind if there was some way to test out the resulting packages a bit and check that they're all working well.

**Comment by pkgw** [comment]
OK, let's put this in. Most of the churn in the recipe is related to the test suite, although we do have a backport related to `FC_DEFAULT_FONTS` that we should keep an eye on.

**Pull request merged**
